export const tokyoNight = {
  'code[class*="language-"]': {
    color: '#c0caf5',
    textShadow: 'none',
    fontFamily: 'Menlo, Monaco, Consolas, "Andale Mono", "Ubuntu Mono", monospace',
    direction: 'ltr',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    lineHeight: '1.5',
    MozTabSize: '4',
    OTabSize: '4',
    tabSize: '4',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    msHyphens: 'none',
    hyphens: 'none'
  },
  'pre[class*="language-"]': {
    color: '#c0caf5',
    textShadow: 'none',
    fontFamily: 'Menlo, Monaco, Consolas, "Andale Mono", "Ubuntu Mono", monospace',
    direction: 'ltr',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    lineHeight: '1.5',
    MozTabSize: '4',
    OTabSize: '4',
    tabSize: '4',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    msHyphens: 'none',
    hyphens: 'none',
    padding: '1em',
    margin: '.5em 0',
    overflow: 'auto',
    background: 'transparent'
  },
  'comment': { color: '#565f89', fontStyle: 'italic' },
  'prolog': { color: '#565f89' },
  'doctype': { color: '#565f89' },
  'cdata': { color: '#565f89' },
  'punctuation': { color: '#89ddff' },
  'namespace': { opacity: '.7' },
  'property': { color: '#7dcfff' },
  'tag': { color: '#f7768e' },
  'boolean': { color: '#ff9e64' },
  'number': { color: '#ff9e64' },
  'constant': { color: '#ff9e64' },
  'symbol': { color: '#ff9e64' },
  'deleted': { color: '#f7768e' },
  'selector': { color: '#bb9af7' },
  'attr-name': { color: '#bb9af7' },
  'string': { color: '#9ece6a' },
  'char': { color: '#9ece6a' },
  'builtin': { color: '#e0af68' },
  'inserted': { color: '#9ece6a' },
  'operator': { color: '#89ddff' },
  'entity': { color: '#89ddff', cursor: 'help' },
  'url': { color: '#89ddff' },
  '.language-css .token.string': { color: '#89ddff' },
  '.style .token.string': { color: '#89ddff' },
  'variable': { color: '#c0caf5' },
  'atrule': { color: '#bb9af7' },
  'attr-value': { color: '#9ece6a' },
  'function': { color: '#7aa2f7' },
  'class-name': { color: '#e0af68' },
  'keyword': { color: '#bb9af7' },
  'regex': { color: '#b4f9f8' },
  'important': { color: '#f7768e', fontWeight: 'bold' },
  'bold': { fontWeight: 'bold' },
  'italic': { fontStyle: 'italic' }
};
